### ISSUE TITLE
Generator Switch

### ISSUE THREAD

**Issue by arsium** [angus-y/PyIris-backdoor#12]
I'm on linux and i get always the generator for linux not windows

**Comment by ev-ev** [comment]
Have you tried to select the windows base?

**Comment by not-sekiun** [comment]
The framework should autodetect your os as linux and work to switch you to linux mode automatically. In any case you can change if from linux mode to windows mode maually if you want. In the generator interface run "show options" in there. you should see the Windows option set to False. Run "set Windows True". It should swap you to the windows version of the generator. Please note the generator cannot compile windows executables on linux you can only generate the raw python script. Due to the limitations of pyinstaller, the compiler used by pyiris you can only compile windows exes on windows using the generator and linux elfs on linux there is no cross compilation supported in pyinstaller therefore pyiris cannot cross compile ;-;. Edit: misread

**Comment by arsium** [comment]
Okay thx for the answer !
