### ISSUE TITLE
no module named cv2

### ISSUE THREAD

**Issue by sj1702** [angus-y/PyIris-backdoor#36]
# How and when to create an issue

## Step 1 : Environment information where PyIris was run
- Exact OS Version
- PyIris Version
- Python Version

## Step 2 : What was done before the error
- What commands were ran before the error
- What was the state of the framework before the error (eg. How many listeners active, how many scouts connected, etc.)
- Programs running while PyIris was running
- What was modified in the framework files (If any were modified)

## Step 3 : Evidence and description
- Description of the error
- Screenshot of the error
- Raw text of the error
- Videos or gifs

## Step 4 : Miscellaneous information
- Any miscellaneous information you would like to provide, the more data provided the better

# Note : Do not create an issue if you cannot reproduce the bug, I need to be able to reproduce the bug in order to fix it

──(kali㉿kali)-[~/PyIris-backdoor]
└─$ python3 PyIris.py
[*]Starting...
[+]Using Python Version 3 - OK
[+]All local files imported - OK
[+]OS Linux - OK
[-]Could not import : No module named 'cv2' - Error, missing packages or packages not installed from setup folder

**Comment by not-sekiun** [comment]
you need to pip install the opencv module, there is a requirements file that you need to use to install the required modules with `pip3 install -r setup/linux/requirements.txt`. This repository is software rotting as well since im working on the rewrite right now so make sure youre on python 3.7 i cannot guarantee compatibility with the latest version of python on kali

**Comment by sj1702** [comment]
Ok will do so

 thanks
