### ISSUE TITLE
project

### ISSUE THREAD

**Issue by Chrisvinley** [angus-y/PyIris-backdoor#45]
We need detailed articles on using this project

**Comment by not-sekiun** [comment]
Hi, while I appreciate the interest in this very poorly ageing project, this current version of the project is actively in the process of being slowly deprecated as I work on its next latest major (technically v3) release. Due to this reason, I am no longer actively supporting the current version being hosted here nor will I be providing any documentation for it. 

_However_, the next major release that I am currently working on that will _supersede_ PyIris (code named "Consortium") will significantly change the architecture as a complete from-the-ground-up rewrite with all the features of the current version and _significantly_ more. I will of course be providing lots of documentation for how to use it as well as long term support. Right now this new version is entirely inaccessible to the general public, being a privately hosted repository open to a select few maintainers.

If you are interested, please do star and watch the repository for any changes and updates in the meantime.

Oh and heres a preview of the documentation landing page if you are interested in what the new version is all about.

![Screenshot 2024-11-02 201513](https://github.com/user-attachments/assets/fecbd640-9f98-4ae0-98dc-b2fbebcb3bc5)
